### PR TITLE
- Add --ignore-folders 

### PR DESCRIPTION
**Pull request by karantan**
Added option which allows the user to specify a list of folders to ignore (e.g. myProject/tests)

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Is the purpose to only have the naming checks ignore those folders?

**Comment by karantan** [comment]
@sigmavirus24 yes.

I will also add ignore-conventions so you will be able to specify which conventions will be skipped / ignored.

**Comment by sigmavirus24** [comment]
@karantan no other plugin to flake8 currently provides this (as far as I'm aware) and other plugins use the `select` and `ignore` flags for flake8 to ignore error-codes from pep8, pyflakes, and all plugins. Why are you seeking to add these flags when flake8 already (for the most part) supports these use-cases?

**Comment by zupo** [comment]
@sigmavirus24 My use case for this is to be able to ignore "N802 function name should be lowercase" inside my tests (because I like to be creative with test method naming), but enforce it everywhere else in my codebase.

**Comment by sigmavirus24** [comment]
I don't think this is appropriate in pep8-naming. This is something that *might* be better suited to Flake8, but would need a nuanced approach.

My main concern with adding this to pep8-naming is that other Flake8 plugins will adopt the same thing. I'm fairly certain optparse will complain if we try to doubly register the same option name with different descriptions so if this is something plugins want to ignore, it might be best to have it as a flag in Flake8 proper to have one flag to rule them all that plugins can use. That said, Flake8 generally does not provide flags by default that are no-op flags, so I'm not sure it makes sense there either.

**Comment by zupo** [comment]
Solved with https://pypi.python.org/pypi/flake8-putty.

**Pull request closed without merging**
