### PR TITLE
Include license

### PR DESCRIPTION
**Pull request by jakirkham**
Add license file to `MANIFEST.in` to ensure it is included in packages.

### CODE REVIEW

**Comment by jakirkham** [comment]
I can't see how the failures are even remotely related to this change.

**Comment by jakirkham** [comment]
Friendly nudge. Can this be merged?

**Comment by sigmavirus24** [comment]
Sorry about that @jakirkham! Thanks for the nudge and the PR!

**Comment by jakirkham** [comment]
Not a problem. Thanks for taking a look @sigmavirus24. 😀

**Pull request merged**
